'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан программным средством.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создается повторно. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ForgotPassword


    '''<summary>
    '''Элемент управления loginForm.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents loginForm As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Элемент управления ErrorMessage.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Элемент управления FailureText.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents FailureText As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Элемент управления Email.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents Email As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Элемент управления DisplayEmail.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents DisplayEmail As Global.System.Web.UI.WebControls.PlaceHolder
End Class
