'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан программным средством.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создается повторно. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagePassword

    '''<summary>
    '''Элемент управления setPassword.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents setPassword As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Элемент управления password.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Элемент управления confirmPassword.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents confirmPassword As Global.System.Web.UI.WebControls.TextBox    

    '''<summary>
    '''Элемент управления changePasswordHolder.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents changePasswordHolder As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''Элемент управления CurrentPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents CurrentPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Элемент управления CurrentPassword.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents CurrentPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Элемент управления NewPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents NewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Элемент управления NewPassword.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents NewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Элемент управления ConfirmNewPasswordLabel.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents ConfirmNewPasswordLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Элемент управления ConfirmNewPassword.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents ConfirmNewPassword As Global.System.Web.UI.WebControls.TextBox
End Class
