'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан программным средством.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создается повторно. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site_Mobile

    '''<summary>
    '''Элемент управления Head1.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''Элемент управления HeadContent.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''элемент управления form1.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Элемент управления FeaturedContent.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents FeaturedContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Элемент управления MainContent.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Элемент управления ViewSwitcher1.
    '''</summary>
    '''<remarks>
    '''Автоматически созданное поле.
    '''Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    '''</remarks>
    Protected WithEvents ViewSwitcher1 As Global.System.Web.UI.UserControl
End Class
