<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="boln.aspx.vb" Inherits="site2013.boln" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        .auto-style2 {
            color: #FF0000;
        }
        .auto-style3 {}
        .auto-style4 {
            text-decoration: underline;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

     <h4>Листок нетрудоспособности (больничный лист)
     </h4>
     <p class="auto-style2"><strong>Внимание! Перед обращением за медицинской помощью с выдачей листка нетрудоспособности, запросите в Вашей бухгалтерии или отделе кадров <span class="auto-style3"><span class="auto-style4">точное Юридическое наименование организации Вашего работодателя</span> для правильного оформления документа</span>.</strong></p>
     <h1 style="margin: 0px; padding: 0px 20px 10px; font-size: 14px; line-height: 19.6000003814697px; text-transform: uppercase; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-style: normal; font-variant: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">ПОРЯДОК ВЫДАЧИ ЛИСТКОВ НЕТРУДОСПОСОБНОСТИ</h1>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Порядок выдачи листков нетрудоспособности урегулирован приказом Минздравсоцразвития от 29 июня 2011 г. N 624н, а также Федеральным законом «Об основах охраны здоровья граждан в РФ» (ст. 59). Ниже приводим выдержки из данных нормативных актов, содержащие основную информацию о порядке оформления больничного (выдачи листков нетрудоспособности).</p>
     <p class="b" style="margin: 0px; padding: 5px 20px; font-weight: bold; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Кто выдает листки нетрудоспособности</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Листок нетрудоспособности можно получить в любой организации, имеющей лицензию на медицинскую деятельность, включая услуги по экспертизе временной нетрудоспособности.</p>
     <p class="i" style="margin: 0px; padding: 5px 20px; font-style: italic; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Выдают листки нетрудоспособности работники таких организаций:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         <li style="margin: 0px; padding: 0px 0px 5px;">лечащие врачи;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">фельдшеры и зубные врачи, иные работники со средним медицинским образованием в отдельных случаях – по решению органа исполнительной власти субъектов Российской Федерации в области здравоохранения;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">лечащие врачи клиник научно-исследовательских учреждений (институтов), в том числе клиник научно-исследовательских учреждений (институтов) протезирования или протезостроения – по согласованию с Министерством здравоохранения и социального развития Российской Федерации.</li>
     </ul>
     <p class="i" style="margin: 0px; padding: 5px 20px; font-style: italic; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Не выдают листки нетрудоспособности медицинские работники:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         <li style="margin: 0px; padding: 0px 0px 5px;">организаций скорой медицинской помощи;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">организаций переливания крови;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">приемных отделений больничных учреждений;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">бальнеологических лечебниц и грязелечебниц;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">медицинских организаций особого типа (центров медицинской профилактики, медицины катастроф, бюро судебно-медицинской экспертизы);</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">учреждений здравоохранения по надзору в сфере защиты прав потребителей и благополучия человека.</li>
     </ul>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Листок нетрудоспособности выдается в день обращения либо в день закрытия больничного.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         В то же время, листок нетрудоспособности, оформленный для назначения и выплаты пособия по временной нетрудоспособности, по беременности и родам, выдается, как правило, в день закрытия больничного.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Если пациента направляют на лечение в другую медицинскую организацию, то листок нетрудоспособности выдается в день обращения, а продляется и закрывается он уже в той организации, куда направлен пациент.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         В случае длительного лечения медицинская организация выдает новый листок нетрудоспособности (продолжение) и одновременно оформляет предыдущий листок нетрудоспособности для назначения и выплаты пособия по временной нетрудоспособности, беременности и родам.</p>
     <p class="b" style="margin: 0px; padding: 5px 20px; font-weight: bold; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Кто может получить листок нетрудоспособности</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" type="square">
         <li style="margin: 0px; padding: 0px 0px 5px;">работающие по трудовым договорам лица, государственные и муниципальные служащие;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">лица, у которых заболевание или травма наступили в течение 30 календарных дней со дня прекращения работы по трудовому договору, осуществления служебной или иной деятельности либо в период со дня заключения трудового договора до дня его аннулирования;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">члены производственного кооператива, принимающие личное участие в его деятельности;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">священнослужители;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">адвокаты, индивидуальные предприниматели, члены крестьянских (фермерских) хозяйств, частнопрактикующие нотариусы и иные лица, занимающиеся частной практикой, члены семейных (родовых) общин коренных малочисленных народов Севера, добровольно вступившие в правоотношения по обязательному социальному страхованию на случай временной нетрудоспособности и в связи с материнством и уплачивающие за себя страховые взносы в Фонд социального страхования Российской Федерации;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">иные категории лиц, подлежащие обязательному социальному страхованию на случай временной нетрудоспособности и в связи с материнством при условии уплаты ими или за них страховых взносов в Фонд социального страхования Российской Федерации.</li>
     </ul>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Также листок нетрудоспособности выдается:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" type="square">
         <li style="margin: 0px; padding: 0px 0px 5px;">женщинам, уволенным в связи с ликвидацией организаций, в связи с прекращением деятельности в качестве индивидуального предпринимателя, прекращением полномочий нотариусом, занимающимся частной практикой, прекращением статуса адвоката, у которых беременность наступила в течение 12 месяцев до признания их в установленном порядке безработными;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">гражданам, признанным безработными и состоящим на учете в государственных учреждениях службы занятости населения, в случае заболевания, травмы, отравлений и иных состояний, связанных с временной потерей трудоспособности, на время протезирования в условиях стационара, беременности и родов, при усыновлении ребенка;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">застрахованным лицам из числа иностранных граждан и лиц без гражданства, временно пребывающих на территории Российской Федерации, утратившим трудоспособность вследствие несчастного случая на производстве или профессионального заболевания.</li>
     </ul>
     <p class="b" style="margin: 0px; padding: 5px 20px; font-weight: bold; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         В каких случаях можно оформить больничный лист</p>
     <p class="i" style="margin: 0px; padding: 5px 20px; font-style: italic; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Основаниями для получения листка нетрудоспособности могут служить:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" type="circle">
         <li style="margin: 0px; padding: 0px 0px 5px;">заболевания, профессиональные заболевания и травмы, полученные на производстве, отравления;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">прохождение санаторно-курортного лечения;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">необходимость ухода за больным членом семьи;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">карантин;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">протезирование;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">беременность и роды.</li>
     </ul>
     <p class="i" style="margin: 0px; padding: 5px 20px; font-style: italic; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Не выдается листок нетрудоспособности гражданам:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" type="circle">
         <li style="margin: 0px; padding: 0px 0px 5px;">обратившимся за медицинской помощью в медицинскую организацию, если у них не выявлено признаков временной нетрудоспособности;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">проходящим медицинское освидетельствование, медицинское обследование или лечение по направлению военных комиссариатов;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">находящимся под стражей или административным арестом;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">проходящим периодические медицинские осмотры (обследования), в том числе в центрах профпатологии;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">с хроническими заболеваниями вне обострения (ухудшения), проходящим обследование, принимающим различные процедуры и манипуляции в амбулаторно-поликлинических условиях;</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">учащимся образовательных учреждений начального профессионального, среднего профессионального и высшего профессионального образования и учреждений послевузовского профессионального образования.</li>
     </ul>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         В целях настоящей статьи рассмотрим случаи выдачи листков нетрудоспособности при заболеваниях и уходе за больным членом семьи.</p>
     <p class="b" style="margin: 0px; padding: 5px 20px; font-weight: bold; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Выдача листка нетрудоспособности при заболеваниях, травмах, отравлениях и иных состояниях</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Единолично лечащий врач выдает листок нетрудоспособности сроком до 15 дней. Далее больничный продлевается по решению врачебной комиссии. Фельдшер или зубной врач выдают больничный сроком до 10 дней.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         При благоприятном клиническом и трудовом прогнозе больничный может продлеваться до 10 месяцев (при состоянии после травмы и реконструктивных операций), а при лечении туберкулеза – до 12 месяцев.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         При неблагоприятном клиническом и трудовом прогнозе врачи обязаны направить пациента на медико-социальную экспертизу (МСЭ) в целях установления инвалидности в срок не позднее 4 месяцев со дня открытия больничного. При этом больничный закрывается днем, предшествующим дню регистрации документов в бюро МСЭ.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Не допускается выдача листков нетрудоспособности за прошедшие дни, когда гражданин не был освидетельствован медицинским работником. В исключительных случаях решение о выдаче листка нетрудоспособности может быть принято врачебной комиссией.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         При оформлении листка нетрудоспособности в целях соблюдения врачебной тайны указывается только причина временной нетрудоспособности (заболевание, травма или иная причина). По письменному заявлению гражданина в листок нетрудоспособности могут вноситься сведения о диагнозе заболевания.</p>
     <p class="b" style="margin: 0px; padding: 5px 20px; font-weight: bold; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Выдача листка нетрудоспособности по уходу за больным членом семьи</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Листок нетрудоспособности по уходу за больным членом семьи выдается медицинским работником одному из членов семьи (опекуну, попечителю, иному родственнику), фактически осуществляющему уход.</p>
     <p align="justify" style="margin: 0px; padding: 5px 20px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
         Такой листок нетрудоспособности выдается на следующие сроки:</p>
     <ul style="margin: 0px; padding: 5px 20px 5px 50px; line-height: 16px; color: rgb(102, 102, 102); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;" type="square">
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за ребенком в возрасте до 7 лет: при амбулаторном лечении или совместном пребывании одного из членов семьи (опекуна, попечителя, иного родственника) с ребенком в стационарном лечебно-профилактическом учреждении – на весь период острого заболевания или обострения хронического заболевания.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за ребенком в возрасте от 7 до 15 лет: при амбулаторном лечении или совместном пребывании одного из членов семьи (опекуна, попечителя, иного родственника) с ребенком в стационарном лечебно-профилактическом учреждении – на срок до 15 дней по каждому случаю заболевания, если по заключению врачебной комиссии не требуется большего срока.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за ребенком-инвалидом в возрасте до 15 лет: при амбулаторном лечении или совместном пребывании одного из членов семьи (опекуна, попечителя, иного родственника) с ребенком в стационарном лечебно-профилактическом учреждении – на весь период острого заболевания или обострения хронического заболевания.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за детьми в возрасте до 15 лет, инфицированными вирусом иммунодефицита человека, – на весь период совместного пребывания с ребенком в стационарном лечебно-профилактическом учреждении.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за детьми в возрасте до 15 лет: при их болезни, связанной с поствакцинальным осложнением, злокачественными новообразованиями, включая злокачественные новообразования лимфоидной, кроветворной и родственных им тканей – на весь период амбулаторного лечения или совместного пребывания одного из членов семьи (опекуна, попечителя, иного родственника) с ребенком в стационарном лечебно-профилактическом учреждении.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за детьми в возрасте до 15 лет, проживающими в зоне отселения и зоне проживания с правом на отселение, эвакуированными и переселенными из зон отчуждения, отселения, проживания с правом на отселение, включая тех, которые на день эвакуации находились в состоянии внутриутробного развития, а также за детьми первого и последующих поколений граждан, родившимися после радиоактивного облучения одного из родителей, – на все время болезни.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за детьми в возрасте до 15 лет, страдающими заболеваниями вследствие радиационного воздействия на родителей, – на все время болезни.</li>
         <li style="margin: 0px; padding: 0px 0px 5px;">По уходу за членами семьи старше 15 лет: при амбулаторном лечении – на срок до 3 дней, по решению врачебной комиссии – до 7 дней по каждому случаю заболевания.</li>
     </ul>
     <p>&nbsp;</p>


</asp:Content>
