<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="ONFKonkurs.aspx.vb" Inherits="site2013.ONFKonkurs" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <p class="c28" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: center; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Положение о конкурсе «Образ будущего страны»</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">Молодежка ОНФ</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;проводит конкурс «Образ будущего страны»<span>&nbsp;</span><br />
        </span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">в двух номинациях</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">:<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">«эссе»<span>&nbsp;</span></span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">и</span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">&nbsp;«креатив»</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">.</span></p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c18" style="margin: 0px 0px 0px 36pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">Номинация «Эссе»</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Участникам предлагается описать<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">прорывные и амбициозные идеи</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">, видение общественных и государственных институтов через 15-20 лет,<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">новые модели (решения)</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;в экономике и социальной сфере, возможно</span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">&nbsp;предложить альтернативу</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;действующей 
        в стране (регионе) конструкции.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Эссе можно написать на разные темы, связанные с актуальными проблемами страны. Например, описать как создать высокопроизводительные рабочие места, сохранить природу, продолжить освоение космоса. А также можно поразмышлять над тем, какой должен быть парламент будущего, или, например, какую роль в жизни человека завтра будет иметь семья, школа, работа и т.д.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Желательно выбрать конкретную тему и рассмотреть ее с разных сторон. Не описывать «цифровую экономику в России «вообще», а как «интернет вещей» изменит государственные сервисы или образование.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">При этом важно основываться<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">на принципах устойчивого развития</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">, таких как значимость для населения, развитие территорий, повышение эффективности использования ресурсов, внедрение новых технологий, сохранение и создание новых экосистем, благоприятная среда проживания и др. ценности.</span></p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c25" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 0pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Условия участия</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">К участию в конкурсе приглашаются студенты ВУЗов и ССУЗов, молодые специалисты и ученые в возрасте до 35 лет.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Работы принимаются<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">до 10 ноября</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">. Для участия в конкурсе<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">необходимо пройти регистрацию на сайте<span>&nbsp;</span></span><span class="c4 c10" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400; color: rgb(0, 0, 255); text-decoration: underline;"><a class="c20" href="https://www.google.com/url?q=http://molodezhka.onf.ru/&amp;sa=D&amp;ust=1508954531143000&amp;usg=AFQjCNEDWNQHK4D1LCxqKM5gU-2-QQqUWw" style="color: inherit; text-decoration: inherit;">http://molodezhka.onf.ru/</a></span><span class="c4 c17" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400; color: rgb(0, 0, 0);">. 
        После прохождения премодерации<span>&nbsp;</span></span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">на формальное соответствие условиям конкурса работа направляется<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">в экспертный совет</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;на оценку.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Рекомендуемый<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">объем эссе<span>&nbsp;</span></span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">– не более 4 страниц А4.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Предлагаемые<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">темы</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;для написания эссе:</span></p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c29" style="margin: 0px 0px 0px 35.5pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: -21pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;государственное устройство и развитие территорий;</span></p>
    <p class="c5" style="margin: 0px 0px 0px 14.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;качество и эффективность власти;</span></p>
    <p class="c14" style="margin: 0px 0px 0px 35.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: -21pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;экономика и предпринимательство;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;цифровизация экономики;</span></p>
    <p class="c5" style="margin: 0px 0px 0px 14.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;образование и наука;</span></p>
    <p class="c5" style="margin: 0px 0px 0px 14.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;культура и просвещение;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;продовольственная безопасность;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;человек и благоприятная среда проживания;</span></p>
    <p class="c5" style="margin: 0px 0px 0px 14.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;демография и институт семьи;</span></p>
    <p class="c14" style="margin: 0px 0px 0px 35.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: -21pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;духовно-нравственные ценности и воспитание;</span></p>
    <p class="c14 c23" style="margin: 0px 102.7pt 0px 35.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: -21pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;волонтерство и добровольчество;</span></p>
    <p class="c14" style="margin: 0px 0px 0px 35.2pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: -21pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;качество и доступность здравоохранения;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;модернизация ЖКХ;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;благоустройство городской среды;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;экология и окружающий мир;</span></p>
    <p class="c7" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; text-indent: 14.2pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">•&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;общественный контроль;</span></p>
    <ul class="c19 lst-kix_list_1-0" style="padding: 0px; margin: 0px; list-style-type: none; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <li class="c5 c22" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 14.2pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; list-style-position: inside; text-indent: 45pt;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">другие.</span></li>
    </ul>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Отбор победителей</span></p>
    <p class="c15" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.07917; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">1 этап</span></p>
    <p class="c15" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.07917; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Экспертный совет проведет оценку работ по следующим критериям:</span></p>
    <ul class="c19 lst-kix_list_7-0 start" style="padding: 0px; margin: 0px; list-style-type: none; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <li class="c12" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 35.9pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">конкретность, ясность, точность и доступность изложения (0-5 баллов);</span></li>
        <li class="c12" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 35.9pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">наличие конструктивных идей и предложений (0-5 баллов);</span></li>
        <li class="c12" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 35.9pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">грамотность, логичность, аргументированность (0-5 баллов);</span></li>
        <li class="c8" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 35.9pt; padding-top: 0pt; padding-bottom: 6pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">оригинальность идеи (0-5 баллов).</span></li>
    </ul>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">По итогам оценки экспертный совет отбирает<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">ТОП-50</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;работ (лауреаты), которые будут размещены на сайте ОНФ в разделе «Молодежка ОНФ»<span>&nbsp;</span></span><span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">для открытого голосования.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c1 c27" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700; text-decoration: underline;">2 этап</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">По итогам открытого голосования<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">жюри конкурса</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;из<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">ТОП-50</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;работ<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">определит победителей<span>&nbsp;</span></span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">конкурса<span>&nbsp;</span></span><span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">до 
        1 декабря.</span></p>
    <p class="c18 c21" style="margin: 0px 0px 0px 36pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;"></span>
    </p>
    <p class="c18" style="margin: 0px 0px 0px 36pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">Номинация «Креатив»</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Участникам предлагается выразить свое видение того, как в будущем будут выглядеть разные общественные явления - будь то любовь к Родине, развитие массового спорта или появление новых профессий.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">К участию принимаются такие креативные работы как<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">стихи, рассказы, рисунки, видеоролики, фотоколлажи и фоторепортажи</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">, которые раскроют будущие тенденции,<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">сотворят образы</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">. Идеи могут быть направлены на созидание, взаимопомощь, справедливость и равные возможности, сочувствие к людям, бережное отношение к окружающему миру, возможно определят 
        альтернативное развитие общества и страны.</span></p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p id="h.gjdgxs" class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Условия участия &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">В конкурсе могут принять участие все желающие в возрасте до 35 лет.</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Работы принимаются<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">до 10 ноября</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">. Для участия в конкурсе<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">необходимо пройти регистрацию на сайте<span>&nbsp;</span></span><span class="c4 c10" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400; color: rgb(0, 0, 255); text-decoration: underline;"><a class="c20" href="https://www.google.com/url?q=http://molodezhka.onf.ru/&amp;sa=D&amp;ust=1508954531152000&amp;usg=AFQjCNFMws2atyIXgGeenjYo1w5X9EabgA" style="color: inherit; text-decoration: inherit;">http://molodezhka.onf.ru/</a></span><span class="c4 c17" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400; color: rgb(0, 0, 0);">. 
        После прохождения премодерации<span>&nbsp;</span></span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">на формальное соответствие условиям конкурса работа<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">размещается в открытом доступе</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;в разделе «Молодежка ОНФ».</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Рекомендуемый объем для работ: стих не более 3 страниц А-4, рассказ не более 4 страницы А-4, видеоролик и фоторепортаж продолжительностью не более 3 минут.</span></p>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">Отбор победителей</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c1 c3" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">1 этап</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">Открытое голосование</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;на сайте ОНФ в разделе «Молодежка ОНФ». По итогам открытого голосования отбирается<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">ТОП-50</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;работ (лауреаты).</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">2 этап</span></p>
    <p class="c9" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Из<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">ТОП-50</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;работ<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">жюри конкурса</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">&nbsp;определяет<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">победителей</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;по следующим критериям:</span></p>
    <ul class="c19 lst-kix_list_8-0 start" style="padding: 0px; margin: 0px; list-style-type: none; color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <li class="c16" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 21.4pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">оригинальность идеи (0-5 баллов);</span></li>
        <li class="c16" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 21.4pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">конкретность, ясность, точность и доступность изложения (0-5 баллов);</span></li>
        <li class="c16" style="color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; margin-left: 21.4pt; padding-top: 0pt; padding-bottom: 3pt; line-height: 1; orphans: 2; widows: 2; text-align: justify;"><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">язык, стилистика, творческие находки и художественность исполнения (0-5 баллов).</span></li>
    </ul>
    <p class="c6" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; height: 11pt; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;"></span>
    </p>
    <p class="c18" style="margin: 0px 0px 0px 36pt; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 0pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: left; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c3 c1" style="color: rgb(0, 0, 0); text-decoration: underline; vertical-align: baseline; font-style: normal; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">Призы</span></p>
    <p class="c11" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 6pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Итоги конкурса будут подведены<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">до 1 декабря.<span>&nbsp;</span></span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">В состав экспертного совета и жюри войдут представители научного сообщества, деятели культуры, эксперты ОНФ и другие общественные деятели.</span></p>
    <p class="c11" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 6pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Работы 50 лауреатов в номинации «Эссе» будут опубликованы в<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">сборнике «Образ будущего страны глазами молодых».</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;</span></p>
    <p class="c11" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 6pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Работы лауреатов в номинации «Креатив» будут представлены<span>&nbsp;</span></span><span class="c0" style="color: rgb(0, 0, 0); font-weight: 700; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">на выставке итогового Форума действий ОНФ в 2017 г.</span></p>
    <p class="c11" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 6pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Лауреаты и победители получат<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">благодарность ОБЩЕРОССИЙСКОГО НАРОДНОГО ФРОНТА, ценные призы и подарки</span><span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">.</span></p>
    <p class="c11" style="margin: 0px; color: rgb(0, 0, 0); font-size: 11pt; font-family: Calibri; padding-top: 6pt; padding-bottom: 6pt; line-height: 1.15; orphans: 2; widows: 2; text-align: justify; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="c4" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 400;">Победители конкурса примут участие<span>&nbsp;</span></span><span class="c1" style="font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-weight: 700;">в итоговом Форуме действий ОНФ в 2017 г.,</span><span class="c2" style="color: rgb(0, 0, 0); font-weight: 400; text-decoration: none; vertical-align: baseline; font-size: 14pt; font-family: &quot;Times New Roman&quot;; font-style: normal;">&nbsp;а также получат возможность принять участие в молодежных образовательных форумах.</span></p>
    <div style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <br class="Apple-interchange-newline" />
    </div>

</asp:Content>
