'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код был создан программным средством.
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создается повторно. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Элемент управления SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Автоматически созданное поле.
    ''' Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Элемент управления ChangePassword.
    ''' </summary>
    ''' <remarks>
    ''' Автоматически созданное поле.
    ''' Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Элемент управления CreatePassword.
    ''' </summary>
    ''' <remarks>
    ''' Автоматически созданное поле.
    ''' Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Элемент управления PhoneNumber.
    ''' </summary>
    ''' <remarks>
    ''' Автоматически созданное поле.
    ''' Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
